DROP TABLE IF EXISTS customer_info_item;
CREATE TABLE customer_info_item
(
    id                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '客户ID',
    name                  VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '姓名',
    mobile                VARCHAR(16)  NOT NULL DEFAULT '' COMMENT '手机号',
    mobile_md5            VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '手机号MD5',
    mobile_area           VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '手机号归属地',
    sex                   TINYINT(4)   NOT NULL DEFAULT 0 COMMENT '性别。 0:保密, 1:男, 2:女',
    age                   TINYINT               DEFAULT NULL COMMENT '年龄',
    id_card_no            VARCHAR(32)           DEFAULT '' COMMENT '身份证号',
    birthday              VARCHAR(10)           DEFAULT '' COMMENT '出生日期。 yyyy-MM-dd 格式',
    req_loan_amount       INT COMMENT '目标贷款金额，单位元',
    house_flag            TINYINT               DEFAULT 0 COMMENT '房产标识。0:未知; 1:有京房; 2:有房; 3:无',
    Insurance_flag        TINYINT               DEFAULT 0 COMMENT '保单标识。0:未知; 1:有; 2:无',
    social_insurance_flag TINYINT               DEFAULT 0 COMMENT '社保标识。0:未知; 1:有; 2:无',
    car_flag              TINYINT               DEFAULT 0 COMMENT '车产标识。0:未知; 1:有; 2:无',
    provident_flag        TINYINT               DEFAULT 0 COMMENT '公积金标识。0:未知; 1:有; 2:无',
    credit_card_flag      TINYINT               DEFAULT 0 COMMENT '信用卡标识。0:未知; 1:有; 2:无',
    enterprise_flag       TINYINT               DEFAULT 0 COMMENT '企业主标识。0:未知; 1:是; 2:否',
    marriage_status       TINYINT               DEFAULT 0 COMMENT '婚姻状态. 0:未知; 1:已婚; 2:未婚; 3:离异',
    provident_amount_yuan INT COMMENT '公积金金额， 单位元',
    house_val             INT COMMENT '房产价值，单位万元',

    car_no                VARCHAR(16)  NOT NULL DEFAULT '' COMMENT '车牌号',
    car_purchase_type     VARCHAR(16)  NOT NULL DEFAULT '' COMMENT '购车方式。 见业务枚举定义',
    city_id               VARCHAR(8)   NOT NULL DEFAULT '' COMMENT '申请人城市ID',
    city_name             VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '申请人城市名称',

    progress              INT          NOT NULL DEFAULT 1 COMMENT '跟进状态。 见业务字典定义',
    address               TEXT COMMENT '住址',
    work_address          TEXT COMMENT '工作单位',
    source_file_name      VARCHAR(200)          DEFAULT '' COMMENT '数据来源文件名称',
    channel               INT                   DEFAULT 0 COMMENT '推广渠道ID。见业务字典定义',
    call_tips             TINYINT      NOT NULL DEFAULT 0 COMMENT '电话结果。见业务字典定义',
    customer_group        INT          NOT NULL DEFAULT 0 COMMENT '客户分组，见业务字典定义',
    follower_user_id      BIGINT       NOT NULL DEFAULT 0 COMMENT '最后一次跟进人用户ID',
    follow_time           DATETIME COMMENT '最后一次跟进时间',
    follow_remark         TEXT COMMENT '跟进情况备注',
    follow_cnt            INT          NOT NULL DEFAULT 0 COMMENT '跟进次数',
    leader_remark         VARCHAR(512) NOT NULL DEFAULT '' COMMENT '上级评价',
    customer_remark       VARCHAR(255) NOT NULL DEFAULT '' COMMENT '客户备注',
    call_remark           VARCHAR(255) NOT NULL DEFAULT '' COMMENT '电话备注',
    apply_date            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间（进本平台件的时间）',
    owner_user_id         BIGINT       NOT NULL DEFAULT 0 COMMENT '当前数据归属人用户ID',
    owner_dept_id         BIGINT       NOT NULL DEFAULT 0 COMMENT '当前数据归属部门ID',
    owner_favorite        TINYINT      NOT NULL DEFAULT 0 COMMENT '收藏标识。 0:再分配客户; 1:我的客户; 2:重点客户 ',
    gmt_create            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    gmt_modified          DATETIME              DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    version               BIGINT       NOT NULL DEFAULT 0 COMMENT '数据版本信息.用于乐观锁',
    PRIMARY KEY (id),
    UNIQUE KEY unq_mobile_name (mobile, NAME),
    INDEX                 IDX_FOLLOW_TIME (follow_time),
    INDEX                 IDX_APPLY_DATE (apply_date),
    INDEX                 IDX_NAME (NAME),
    INDEX                 IDX_OWNER_USER_ID (owner_user_id),
    INDEX                 IDX_OWNER_DEPT_ID (owner_dept_id),
    INDEX                 IDX_CUSTOMER_GROUP_ID (customer_group),
    INDEX                 IDX_ID_CARD_NO (id_card_no),
    INDEX                 IDX_PROGRESS (progress),
    INDEx                 IDX_MOBILE_MD5 (mobile_md5),
    INDEX                 IDX_CHANNEL (channel)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='客户信息数据';

-- 生产环境已执行 20251207
-- ALTER TABLE customer_info_item
--     ADD COLUMN mobile_md5 VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手机号MD5' AFTER mobile,
--     ADD COLUMN     car_no VARCHAR(16) NOT NULL DEFAULT '' COMMENT '车牌号' AFTER house_val,
--     ADD COLUMN car_purchase_type VARCHAR(16) NOT NULL DEFAULT '' COMMENT '购车方式。 见业务枚举定义' AFTER car_no,
--     ADD COLUMN city_id VARCHAR(8) NOT NULL DEFAULT '' COMMENT '申请人城市ID' AFTER car_purchase_type,
--     ADD COLUMN city_name VARCHAR(32) NOT NULL DEFAULT '' COMMENT '申请人城市名称' AFTER city_id,
--     ADD INDEx idx_mobile_md5 (mobile_md5);
