DROP TABLE IF EXISTS `biz_order`;

CREATE TABLE `biz_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `customer_id` bigint NOT NULL COMMENT '客户ID',
  `platform_id` bigint NOT NULL COMMENT '平台ID',
  `device_model` varchar(128) NOT NULL COMMENT '设备型号',
  `status` varchar(32) NOT NULL COMMENT '订单状态',
  `down_payment_amount` decimal(10,2) DEFAULT '0.00' COMMENT '首付款金额',
  `is_down_payment_advanced` tinyint(1) DEFAULT '0' COMMENT '是否垫付首付',
  `recycle_price` decimal(10,2) DEFAULT '0.00' COMMENT '回收价/尾款支出',
  `resale_price` decimal(10,2) DEFAULT '0.00' COMMENT '出售价/变现收入',
  `gross_profit` decimal(10,2) DEFAULT '0.00' COMMENT '毛利润',
  `tracking_no_platform` varchar(64) DEFAULT NULL COMMENT '平台发货物流单号',
  `tracking_no_customer` varchar(64) DEFAULT NULL COMMENT '客户转寄物流单号',
  `owner_user_id` bigint DEFAULT NULL COMMENT '归属人ID',
  `owner_dept_id` bigint DEFAULT NULL COMMENT '归属部门ID',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `platform_recv_province` varchar(64) DEFAULT NULL COMMENT '平台收件省',
  `platform_recv_city` varchar(64) DEFAULT NULL COMMENT '平台收件市',
  `platform_recv_district` varchar(64) DEFAULT NULL COMMENT '平台收件区县',
  `platform_recv_street` varchar(64) DEFAULT NULL COMMENT '平台收件街道',
  `platform_recv_detail` varchar(255) DEFAULT NULL COMMENT '平台收件详细地址',
  `self_recv_province` varchar(64) DEFAULT NULL COMMENT '我方收件省',
  `self_recv_city` varchar(64) DEFAULT NULL COMMENT '我方收件市',
  `self_recv_district` varchar(64) DEFAULT NULL COMMENT '我方收件区县',
  `self_recv_street` varchar(64) DEFAULT NULL COMMENT '我方收件街道',
  `self_recv_detail` varchar(255) DEFAULT NULL COMMENT '我方收件详细地址',
  `device_quantity` int NOT NULL DEFAULT '1' COMMENT '数量',
  `agreed_recycle_price` decimal(10,2) DEFAULT '0.00' COMMENT '约定回收价',
  `channel_commission` decimal(10,2) DEFAULT '0.00' COMMENT '渠道返佣',
  PRIMARY KEY (`id`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_owner_user_id` (`owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业务订单表';
