package com.jhl.silver.union.web.data.user;

import com.jhl.silver.union.web.data.IValidateRequest;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * This class was generated by MyBatis Generator.
 * 对应表: ju_user_info
 * 
 * @author: Mybatis-generator
 * @create_time: 2020/10/21
 */
@Data
@Accessors(chain = true)
@Schema(description = "用户登录请求")
public class EntUserLoginRequest implements IValidateRequest {

    /**
     * 字段: userName 用户名,即用户自定义账号
     */
    @Schema(description = "用户名", type = "String", requiredMode = Schema.RequiredMode.REQUIRED)
    @NotBlank(message = "请输入用户名")
    private String username;

    /**
     * 字段: password 用户密码。 存储散列后的密码值
     */
    @Schema(description = "用户密码", type = "String", requiredMode = Schema.RequiredMode.REQUIRED)
    @NotBlank(message = "请输入密码")
    private String password;

    // private String clientId;
    //
    // private String clientSecret;
}