upstream silver_union_web{
    server 127.0.0.1:32800;
}

server  {
    listen       443 ssl http2;
    server_name  crm.zhudai.pro;
    index index.jsp index.htm index.html;
    root /data/www/su-ops/dist;

    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    ssl_certificate    /etc/nginx/cert/crm.zhudai.pro/crm.zhudai.pro.20250711.pem;
    ssl_certificate_key    /etc/nginx/cert/crm.zhudai.pro/crm.zhudai.pro.20250711.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    #SSL-END

    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }
    location ^~/api/ {

           proxy_pass              http://silver_union_web/api/;
           proxy_set_header        X-Real-IP $remote_addr;
           proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header        Host $http_host;
           proxy_set_header        X-Forwarded-Proto $scheme;
           proxy_read_timeout      45;
           proxy_send_timeout      60;
           expires 0m;
    }

    location / {
        index index.html index.htm;
        try_files $uri $uri/ @router;
    }

    location @router {
        rewrite ^.*$ /index.html last;
    }
  }

server {
    listen 80;
    server_name crm.zhudai.pro;
    return     301 https://crm.zhudai.pro$request_uri;
}